### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by TomAugspurger**
So I started on the modern pandas thing this weekend, and realized I didn't *really* want to write an entire intro-to-pandas when we've got your resources. So I figured it'd be less work (for me) to update your notebooks. I'll do the others this week if you're on board.

Since diffing notebooks sucks, I converted master and this version to markdown and [diffed the two](https://gist.github.com/TomAugspurger/c8391b217c28fa5978a4). I didn't have all the files, so I couldn't run all the cells. I don't think I broke anything though.

There were a few py3 changes (maybe just print statements), a few deprecations `.sort / .order vs .sort_values`. A small note on `.inplace` (I'm going to be recommending against it in my series).

The biggest change was removing the use of `.ix` and replacing it with `.loc` and `.iloc`. Hopefully you're cool with that :) 

I did clear all the output before submitting, because I didn't want to mess up all the numbering. I think you'll have to re-execute the notebook to use it with Jake's liquid tags plugin.

### CODE REVIEW

**Comment by gjreda** [comment]
This is awesome - thank you for doing that. I'll take a closer look this weekend, but everything looks good for a merge at first glance.

Regarding modern pandas, maybe it makes sense to add a "part 4" or something to this series, which is something I might have time to write. I had been away from Python for a bit, but have been doing _a lot_ of work in pandas again and am realizing there are so many great things this series doesn't touch on -- resampling, time-series, etc.

Thoughts?

**Comment by TomAugspurger** [comment]
I'll be touching on resampling in my post / posts, since that got a rework in 0.18. Hopefully I'll have at least drafts done this week, and then you can decide whether it makes sense to add another section (I'd say go for it).

**Comment by gjreda** [comment]
Ohhh, I misread your first post -- thought you were saying you didn't really want to write `modern pandas`. No need for me to write another part then -- all you. :raised_hands:

**Comment by TomAugspurger** [comment]
:+1: 

Also I didn't realize that all 3 parts were in the one notebook, so it should pretty much be good to go.

**Comment by gjreda** [comment]
Were you using a newer version of a IPython / Jupyter notebook by chance? IIRC, I think the liquid tags plugin only works with some super old version. I'm on 1.2.1.

**Comment by TomAugspurger** [comment]
Whoops yeah I was on the most recent version :/

**Comment by gjreda** [comment]
Blah. I'll see if I can get it sorted out with the newer version, but if not, I'll just make the changes in my notebook -- at least I know all that needs to be changed now. Thank you again.

**Comment by gjreda** [comment]
Wasn't worth the effort to try figuring it out, so I just did it all manually. Much appreciated.

**Pull request merged**
